name: ody_flutter
description: "오디 프로젝트"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.16
  intl: ^0.20.1
  path: ^1.9.0
  provider: ^6.1.2
  smooth_page_indicator: ^1.2.1
  sqflite: ^2.4.1
  table_calendar: ^3.1.3
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - .env

  fonts:
    - family: PretendardBold
      fonts:
        - asset: assets/fonts/pretendard-bold.ttf
    - family: PretendardMedium
      fonts:
        - asset: assets/fonts/pretendard-medium.ttf
    - family: PretendardRegular
      fonts:
        - asset: assets/fonts/pretendard-regular.ttf

  uses-material-design: true
