name: ody_flutter
description: "오디 프로젝트"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  http: ^1.2.2
  intl: ^0.20.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/

  fonts:
    - family: PretendardBold
      fonts:
        - asset: assets/fonts/pretendard-bold.ttf
    - family: PretendardMedium
      fonts:
        - asset: assets/fonts/pretendard-medium.ttf
    - family: PretendardRegular
      fonts:
        - asset: assets/fonts/pretendard-regular.ttf

  uses-material-design: true
