name: Flutter CI

on:
  pull_request:
    branches: [ "develop" ]

defaults:
  run:
    working-directory: ody_flutter

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Use Xcode 15.3
        run: sudo xcode-select -s /Applications/Xcode_15.3.app

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install flutter sdk
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Add firebase.json
        run: echo '${{ secrets.FIREBASE_JSON }}' > ./firebase.json

      - name: Add google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICE_JSON }}' > ./android/app/google-services.json

      - name: Add GoogleService-info.plist
        run: echo '${{ secrets.GOOGLE_SERVICE_INFO }}' > ./ios/Runner/GoogleService-info.plist

      - name: Install dependencies
        run: flutter pub get

      - name: Lint check
        run: flutter analyze

      - name: Run test
        run: |
          touch .env
          flutter test

      - name: Build iOS
        run: flutter build ios --no-codesign
