name: Flutter CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Install flutter sdk
        uses: subosito/flutter-action@v2
        with:
          channel: stable
        
      - name: Install dependencies
        uses: actions/checkout@v4
        run: flutter pub get
        
      - name: Run lint checkout
        run: flutter analyze --fail-on-lint

      - name: Run test
        run: flutter test

      # Build iOS without code signing
      - name: Build iOS
        run: flutter build ios --no-codesign

      # Build Andriod without shrink
      - name: Build Andriod
        run: flutter build apk --no-shrink
