name: Flutter CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install flutter sdk
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: |
          cd ody_flutter
          flutter pub get

      - name: Run lint check
        run: |
          cd ody_flutter
          flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Run test
        run: |
          cd ody_flutter
          flutter test
          
      # Build iOS without code signing
      - name: Build iOS without code signing
        run: |
          cd ody_flutter
          flutter build ios --no-codesign

      # Build Andriod without shrink
      - name: Build Android without shrink
        run: |
          cd ody_flutter
          flutter build apk --no-shrink
